FROM php:7.0-fpm
# Install “curl”, “libmemcached-dev”, “libpq-dev”, “libjpeg-dev”,
# “libpng12-dev”, “libfreetype6-dev”, “libssl-dev”, “libmcrypt-dev”,
RUN apt-get update && \
    apt-get install -y — no-install-recommends \
    curl \
    libmemcached-dev \
    libz-dev \
    libpq-dev \
    libjpeg-dev \
    libpng12-dev \
    libfreetype6-dev \
    libssl-dev \
    libmcrypt-dev
# Install the PHP mcrypt extention
# Install bcmath extension
RUN docker-php-ext-install bcmath
# Install the PHP gd library
RUN docker-php-ext-configure gd \
    — enable-gd-native-ttf \
    — with-jpeg-dir=/usr/lib \
    — with-freetype-dir=/usr/include/freetype2 && \
    docker-php-ext-install gd
# Install the php memcached extension
RUN curl -L -o /tmp/memcached.tar.gz “https://github.com/php-memcached-dev/php-memcached/archive/php7.tar.gz" \
    && mkdir -p memcached \
    && tar -C memcached -zxvf /tmp/memcached.tar.gz — strip 1 \
    && ( \
    cd memcached \
    && phpize \
    && ./configure \
    && make -j$(nproc) \
    && make install \
    ) \
    && rm -r memcached \
    && rm /tmp/memcached.tar.gz \
    && docker-php-ext-enable memcached
# Permissions
ARG PUID=5082
RUN usermod -u ${PUID} www-data
ADD start.sh /start.sh
RUN chmod +x /start.sh
USER www-data
WORKDIR /var/www/laravel
CMD [“/start.sh”]
